// frontend/src/components/ArticleCard.tsx
import { useState } from 'react'
import type { Deliverable } from '../api/client'

export function scoreColor(score: number): 'green' | 'amber' | 'red' {
  if (score >= 80) return 'green'
  if (score >= 60) return 'amber'
  return 'red'
}

export function ArticleCard({ d }: { d: Deliverable }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="article-card">
      <div className="article-head">
        <h3>{d.title}</h3>
        <span className={`score score-${scoreColor(d.review.score)}`}>{d.review.score}</span>
      </div>
      <p className="verdict">{d.review.verdict === 'accept' ? 'Принято' : 'На доработку'}</p>
      <p className="cta">{d.cta}</p>
      <button onClick={() => setOpen(true)}>Читать ▸</button>
      {open && (
        <div className="modal" role="dialog" onClick={() => setOpen(false)}>
          <div className="modal-body" onClick={(e) => e.stopPropagation()}>
            <h3>{d.title}</h3>
            <p className="article-body">{d.body}</p>
            {d.review.issues && d.review.issues.length > 0 && (
              <>
                <h4>Замечания критика</h4>
                <ul>{d.review.issues.map((i, k) => <li key={k}>{i}</li>)}</ul>
              </>
            )}
            <p className="cta">{d.cta}</p>
            <button onClick={() => setOpen(false)}>Закрыть</button>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/lib/components/ArticleCard.svelte
<script lang="ts">
	import Modal from './Modal.svelte';
	import ScoreBadge from './ScoreBadge.svelte';
	import { ARTICLE_VERDICT_LABELS } from '#lib/labels.js';
	import type { Deliverable } from '#lib/api/types.js';

	let { deliverable }: { deliverable: Deliverable } = $props();

	let open = $state(false);
</script>

<div class="article-card">
	<div class="article-head">
		<h3>{deliverable.title}</h3>
		<ScoreBadge score={deliverable.review.score} severity={deliverable.review.severity} />
	</div>
	<p class="verdict">{ARTICLE_VERDICT_LABELS[deliverable.review.verdict] ?? deliverable.review.verdict}</p>
	<p class="cta">{deliverable.cta}</p>
	<button type="button" class="btn btn-secondary" onclick={() => (open = true)}>Читать ▸</button>

	<Modal {open} title={deliverable.title} onClose={() => (open = false)}>
		<p class="article-body">{deliverable.body}</p>
		{#if deliverable.review.issues && deliverable.review.issues.length > 0}
			<h4>Замечания критика</h4>
			<ul class="issues">
				{#each deliverable.review.issues as issue, i (i)}
					<li>{issue}</li>
				{/each}
			</ul>
		{/if}
		<p class="cta">{deliverable.cta}</p>
	</Modal>
</div>
